### ISSUE TITLE
Error on installation. Can't access the dashboard and the reports page on the control panel

### ISSUE THREAD

**Issue by edwardpmartinez** [barrelstrength/craft-sprout-reports#84] opened 2020-05-03 09:39 UTC
### Description (screenshots, logs, ...)

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sitename.sproutreports_datasources' doesn't exist
The SQL being executed was: SELECT *
FROM `sproutreports_datasources`
Error Info: Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'sitename.sproutreports_datasources' doesn't exist

### Steps to reproduce

1. Fresh install of Sprouts Reports from plugins page
2. Click on Reports on the control panel

### Additional info

- Craft version: 3.4.17.1
- PHP version: 7.2.30
- Database driver & version:  MySQL 5.7.2.9
- Plugins & versions: Sprout reports

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by BenParizek** [comment] 2020-05-03 10:50
@edwardpmartinez I'm not able to reproduce this. 

Can you try the install again and see if you see any errors in the storage/logs/craft.log file after installation?

Maybe you could also confirm that no `sprout_` tables are in the database when you start the installation process and let me know which ones you see in the database after the install happens?

I don't know of a reason why a fresh install wouldn't have this table, the Install script should be adding it and all the other tables in the same way. So I'm wondering if there is something else about your environment that would make this particular table behave differently

**Comment by BenParizek** [comment] 2020-05-20 14:44
As this has gone a few weeks without additional info, I'm going to close it out. Please re-open and add more info if the issue continues.

**Closed by BenParizek** 2020-05-20 14:44 UTC
Labels: c3, question
