### ISSUE TITLE
Problems showing reports after updating to Craft 3

### ISSUE THREAD

**Issue by JayBox325** [barrelstrength/craft-sprout-reports#44] opened 2019-02-20 17:22 UTC
Hi,

We have been generating reports on a Craft 2 with Commerce 1 site for a year now and we've just updated it to Craft 3.

The plugin is showing we have report sources available (6 are imported from old site, 1 is a test):

![screenshot 2019-02-20 at 17 17 28](https://user-images.githubusercontent.com/13233809/53110903-e9957080-3533-11e9-86bd-b83052833589.png)

Yet, when we view our reports in the Reports tab in the CMS we only see the single test report we have run since updating to the Craft 3 site:

![screenshot 2019-02-20 at 17 17 35](https://user-images.githubusercontent.com/13233809/53110947-0762d580-3534-11e9-8d0a-0d6e136d3b0b.png)

Is this a known Commerce reporting issue or is there something we need to do once updated from Craft 2? Cheers

### Additional info

- Craft version: 3.1.12

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_hjjf)

**Comment by JayBox325** [comment] 2019-02-25 15:20
Hi @andrelopez, thanks for acknowledging this ticket. Any idea on a timeframe for reviewing it? Cheers

**Comment by BenParizek** [comment] 2019-02-25 18:52
Hi @JayBox325 

I'd have to see your database tables to be sure but the Craft Commerce reports were a [separate plugin](https://github.com/barrelstrength/craft-sprout-reports-commerce) that integrated with Sprout Reports. It's on our list to migrate them but we just haven't had a chance to prioritize them yet.

So, while not ideal in your situation, this is expected behavior as the Commerce Data Source for Sprout Reports has not yet been updated to support Craft 3 yet.

I'll close out this ticket as we have a ticket open for that here already. Please feel free to add additional comments or follow updates there:
https://github.com/barrelstrength/craft-sprout-reports/issues/42

We don't have an estimated release date for this. While we hope to get to it sooner than later, our supporting plugins are usually driven by project needs and contract work. While I'd consider this higher up on our list, we're still working through several Craft 3.1 related improvements to our plugins and a few other features that are in the works before we get to this. Please drop us a note if you are interested in discussing a [consulting project](https://sprout.barrelstrengthdesign.com/docs/businesses.html) or we'll be sure to update this thread and let you know once we get it released.

**Comment by JayBox325** [comment] 2019-02-25 23:55
Thanks for getting back to me. Will be in touch. Cheers

**Comment by ajgaunt** [comment] 2019-02-26 04:08
Ben,

I just wanted to confirm that this was not specifically for Commerce Reports but Sprout Reports. We are using Custom Queries to generate reports that pull data from Commerce. The count for the custom query reports is correct but they are not showing in the reports section.

**Comment by BenParizek** [comment] 2019-02-26 04:25
Ok, thanks @ajgaunt. I'll reopen.

Could you send a database over to sprout@barrelstrengthdesign.com so we can take a look at what's going on? If you can't send the whole db, can you at least send the Sprout Reports tables?

**Comment by pdaleramirez** [comment] 2019-03-08 03:18
@BenParizek I added migration class for this fixed here on sprout-reports https://github.com/barrelstrength/craft-sprout-reports/commit/9d71de07755b8295316c0f9369af8be20794549c and it is dependent on base reports committed here https://github.com/barrelstrength/craft-sprout-base-reports/commit/e6e765ea73ff04b8e1382dfb3afc3f18c3439aa4

The reason why it is not showing up cause we converted reports record to elements on craft 3. The reports index page is not able to get the element report types.
The class migration will convert craft 2 reports record to craft 3 elements. This should fix the issue

**Comment by BenParizek** [comment] 2019-03-19 16:47
@JayBox325 @ajgaunt If you haven't worked around this by now, the latest Sprout Reports release adds a migration that should address this issue. Thanks for reporting.

**Closed by BenParizek** 2019-03-19 16:47 UTC
Labels: bug, c3

**Comment by BenParizek** [comment] 2019-08-16 16:42
@JayBox325 just to note, recently, we got a basic version of the Commerce Data Source for Sprout Reports plugin updated to C3: https://plugins.craftcms.com/sprout-reports-commerce

**Comment by JayBox325** [comment] 2019-08-19 11:55
Thanks, @BenParizek.

@ajgaunt. One for you, Sire.
